### ISSUE TITLE
Mecab doesn't work

### ISSUE THREAD

**Issue by Kcrong** [goodatlas/konlpy#6]
```python
>>> from goodatlas.konlpy.tag import Mecab
>>> Mecab()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kcrong/atlasguide/virtualenv/env3/lib/python3.6/site-packages/goodatlas/konlpy/tag/_mecab.py", line 107, in __init__
    self.tagset = utils.read_json('%s/data/tagset/mecab.json' % utils.installpath)
  File "/Users/kcrong/atlasguide/virtualenv/env3/lib/python3.6/site-packages/goodatlas/konlpy/utils.py", line 192, in read_json
    with io.open(filename, 'r', encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kcrong/atlasguide/virtualenv/env3/lib/python3.6/site-packages/goodatlas/konlpy/data/tagset/mecab.json'
```

**Comment by Kcrong** [comment]
closed via #7

```python
>>> from goodatlas.konlpy.tag import Mecab
>>> Mecab()
<goodatlas.konlpy.tag._mecab.Mecab object at 0x1019c5710>
>>> Mecab().pos("안녕하세요")
[('안녕', 'NNG'), ('하', 'XSV'), ('세요', 'EP+EF')]
```
